api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: ${LE_EMAIL}
      storage: /acme/acme.json
      dnsChallenge:
        provider: zerossl
        delayBeforeCheck: 0
      caServer: https://acme.zerossl.com/v2/DV90
    tlsChallenge: {}

logs:
  level: INFO
